### PR TITLE
Move lib/replace.js -> index.js

### PR DESCRIPTION
**Pull request by homeyjd**
The hosted/tagged version 0.1.0 does not work with my environment: NPM v1.3.6 / NodeJS v0.10.36.
```
[09:28:05] 'js' errored after 105 ms
[09:28:05] Error: Cannot find module 'lib/replace'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/src/node_modules/gulp-string-replace/index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

If I modify the file index.js with the following line, the error is satisfied. Note the addition of the './' before the module path.
```module.exports = require('./lib/replace')```

This package is small (but very helpful! thank you for writing it!).  Since the module is small enough, I recommend containing all functionality in the primary index.js file.

### CODE REVIEW

**Comment by tomaszczechowski** [comment]
Hey Jesse,

Thank you contributing to this project. I am ok with your proposals and accepted PR.

Cheers.
Tomasz
